# Site settings
name: Peconic Monument Works
title: Peconic Monument Works
email: peconicmonuments@gmail.com
subtitle: "From a marker to a mausoleum - your full service memorial shop"
description: From a marker to a mausoleum - your full service memorial shop
baseurl: "" # the subpath of your site, e.g. /blog/
ga_tracking_id: "UA-78983934-1" # Google analytics
url: "https://www.peconicmonumentworks.com/"
cover: "/assets/shop.png"
logo: "/assets/logo.png"
phone: "631-727-4170"

# Build settings
permalink: pretty
markdown: kramdown
exclude: ["/vendor/"]
inter_post_navigation: false
highlightjs_theme: "monokai_sublime"

# Social sharing protocols
protocols:
    fb_image: "/assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"
    twitter_image: "/assets/logo.png"
